# Site settings

title: Sudoku-Explorer
email: h.bertling@web.de    
description: > # this means to ignore newlines until "baseurl:"
    
    Diese App ist ein Explorer für klassisches 9x9-Sudokus. 
    Mit dem Explorer kannst Du konkrete Puzzles generieren und lösen
    und darüberhinaus die Welt des klassischen 9x9 Sudoku umfassend kennenlernen.

    Viel Vergnügen mit dem Explorer!
    
    Hubert Bertling
    
    

# Build settings
theme: jekyll-theme-cayman
