# Site settings

title: Sudoku-Explorer
email: h.bertling@web.de    
description: > # this means to ignore newlines until "baseurl:"
    Diese App ist ein Explorer für klassisches 9x9-Sudoku. Sie wendet sich einerseits an Gelegenheitsspieler bw. -spielerinnen, 
    die ein Sudoku lösen wollen, das sie beispielsweise in einer Zeitschrift gefunden haben. Dieser Explorer unterstützt Dich 
    beim manuellen Lösen durch Tips, kann aber auch die Lösung voll automatisch durchführen und dabei jeden Lösungsschritt anzeigen.
    
    Mit zunehmender Erfahrung wächst das Interesse an weitergehnden Fragestellungen: 
    Was bedeuten eigentlch die unterschiedlichen Schwierigkeitsgrade von Sudokus? 
    Gibt es für jedes Sudoku eine Lösung? Oder gar mehrere? Kann man alle Sudokus mit Hilfe logischer Schlussregeln lösen? 
    Was bedeutet es, ein Puzzle per Backtracking zu lösen? 
    Mit dem Explorer lernst Du die Welt des klassischen 9x9 Sudoku kennen: die Anwendung logischer Lösungstechniken,
    die Bedeutung der Puzzle-Schwierigkeitsgrade, die Puzzle-Kategorien: "eindeutig lösbar", 
    "mehrfach lösbar" und "unlösbar" und das Backtracking. Der Explorer erzeugt Beispiel-Puzzles für all diee Fälle.

    In der Hilfe der App findest Du Informationen zu 9x9-Sudokus und zur Bedienung der App. Wusstes Du, 
    dass es 6.670.903.752.021.072.936.960 vollständig ausgefüllte 9x9 Sudokus gibt? 
    Oder, dass die minimale Anzahl vorgegebener Zahlen in einem eindeutig lösbaren 9x9-Sudoku 17 ist? 
    Wenn Dich solche Einsichten interessieren, dann schau in die Hilfe und überprüfe die Einsichten an vom Explorer generierten 
    Beispiel-Puzzles. Viel Vergnügen mit dem Explorer beim Sudoku-Lernen und Sudoku-Lösen.

# Build settings
theme: jekyll-theme-cayman
