# Site settings

title: Sudoku-Explorer
email: h.bertling@web.de    
description: > # this means to ignore newlines until "baseurl:"
    
    Diese App ist ein Explorer für klassische 9x9-Sudokus. 
    Mit dem Explorer kannst Du einerseits konkrete Puzzles lösen
    und andererseits über das einzelne Puzzle hinaus die Welt des 
    klassischen 9x9-Sudokus umfassend kennenlernen: 
    Schwierigkeitsgrade, Kandidaten-Eliminierung, Eindeutige oder 
    vielfache Lösungen, Backtracking.

    Viel Vergnügen mit dem Explorer!
    
    Hubert Bertling
    
    

# Build settings
theme: jekyll-theme-cayman
